export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE";
// export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
// export const ADJUST_QTY = "ADJUST_QTY";
// export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";
